### ISSUE TITLE
Termina el ejercicio

### ISSUE THREAD

**Issue by nasivuela** [Adalab/f-m3-evaluacion-intermedia-elvirafuente#1]
Super buen trabajo @elvirafuente 

Algunas pistas para acabarlo:

- [x] Añade un título a la página (Mi lista de Pokemons)
- [x] Evita espacios en tre el corchangulo de apertura y el nombre del componente, ejemplo `< PokeList data={pokemons}/>` => `<PokeList data={pokemons} />`
- [x] Termina de añadir los elementos finales de la tarjeta de cada Pokemon: los tipos tienen que ser una lista, no pueden ser span sueltos, recuerda que son elementos relacionados. Un OL o UL es lo suyo.
- [x] Mueve el `li` fuera del componente 'Pokemon', de esta manera Pokemon es un componente con una tarjeta que podemos usar en diferentes sitios y no solo dentro de un `ul`
- [x] Añade estilos (un archivo sass o css por componente)
- [x] Usa propTypes para comprobar el tipo de dato de las props
- [x] Revisa los metadatos en index.html (lang, title...)
- [x] Limpia e indenta el código
- [x] Publica en Github Pages
- [x] Elimina archivos sin usar y sus referencias

Cuando tengas esto puedes:

1. Mover el array de pokemons a otro archivo e importarlo en App.
2. Inicializar el estado de App con el array de pokemons y utilizar este en lugar de la constante `pokemon`.
3. Añadir un click a Card que: marca o desmarca el pokemon como favorito en el array del estado de App.
4. Pasar este dato a Card por props
5. Pintar la tarjeta con otros estilos cuando por props nos llegue la info de que el pokemon es favorito

Si tienes cualquier duda, avisa!

Al turrón

**Comment by elvirafuente** [comment]
Hello @nasivuela !
Thank you for your feedback :)
I will improve the app in the next few days, but in case you want to check it, the basic issues are already done.
I will let you know as soon as the advanced ones are implemented.

thanks again!
Elvira :)

**Comment by nasivuela** [comment]
Excelente!

Ojo con las propTypes de PokeList que se te han pasado.

A parte de eso lo veo genial! Cierro issue y como siempre te dejo un ejercicio más para practicar:

- Añade una página de detalle para cada Pokemon!

![](https://media.giphy.com/media/GazPMD1iWfgcM/giphy.gif)
